### ISSUE TITLE
windows.h missing trying to compile on Windows 10

### ISSUE THREAD

**Issue by mascondante** [sebastianbiallas/pearpc#13]
I followed https://github.com/sebastianbiallas/pearpc/issues/9 which got me further but I still ultimately failed.

Autogen: https://ghostbin.com/paste/2ofj5
Configure: https://ghostbin.com/paste/89myk
Make: https://ghostbin.com/paste/zgbzo
Using Ubuntu on Windows (the new Linux subsystem for Win10 Anniversary v.1067). Version: Trusty

Thank you so much for all you've done and keeping this project alive.

**Comment by sebastianbiallas** [comment]
You cannot compile a windows program with ubuntu on windows. Use cygwin or something like this.

**Comment by ballo** [comment]
You can compile windows programs with mingw32

**Comment by ballo** [comment]
Here's how:

http://forums.codeblocks.org/index.php?topic=3343.0

**Comment by mascondante** [comment]
Thank you.  Are there any reported issues with Windows 10 and PearPC in general? I can't get it to boot for squat on 0.5. I will compile latest version tomorrow hopefully. Have I made some mistake I'm not seeing?

Config: https://ghostbin.com/paste/rcq77

I remember also I had one set up that worked under Win8 in c:\PearPC.  It doesn't work anymore either.

This is where it stalls: https://ghostbin.com/paste/w6dyw https://www.dropbox.com/s/38y6iz424vcmjuq/Screenshot%202016-11-03%2023.21.24.png?dl=0

No Apple logo, no timeout warning.

Again I cannot stress enough how much I appreciate the work on this project. Thank you for your quick reply earlier.
