### ISSUE TITLE
Small fix to get pearpc to compile with SDL 1.2.15 and C++11

### ISSUE THREAD

**Issue by cat7** [sebastianbiallas/pearpc#5]
C++11 stumbles on a missing space in src/system/ui/SDL/sysdisplay.cc 

#define DPRINTF(a...) ht_printf("[Display/SDL]: "a)

adding a space before "a fixes this:
#define DPRINTF(a...) ht_printf("[Display/SDL]: " a)

**Comment by sebastianbiallas** [comment]
Fixed, thanks
